MODE: 2             # 1: train, 2: test, 3: eval
MASK: 7             # 1: random block, 2: half, 3: external, 4: (external, random block), 5: (external, random block, half)
EDGE: 2             # 1: canny, 2: external
LAYOUT: 1           # 1: GT, 2: horizon-net
LAYOUT_EDGE: 1      # 1: USE layout edge in input, 0: DON'T USE layout edge in input
SEAN: 1             # 1: ON, 0: NO modulation
PLANE: 1            # 1: USE plane-aware normalization, 0: DON'T USE
PARTIAL: 1          # 1: USE PCONV, 0: DON'T USE PCONV (in zencoder)
NMS: 1              # 0: no non-max-suppression, 1: applies non-max-suppression on the external edges by multiplying by Canny
SEED: 11            # random seed
GPU: [0]            # list of gpu ids
DEBUG: 0            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console
FURNISHED: 0        # 0: empty room, 1: furnished room
RESULTS: 

TRAIN_FLIST: ./flists/structured3d_roomtype/structured3d_roomtype/train.flist
VAL_FLIST: ./flists/structured3d_roomtype/structured3d_roomtype/val.flist
TEST_FLIST: 

TRAIN_EDGE_FLIST: ./flists/structured3d_roomtype/structured3d_roomtype/train.flist
VAL_EDGE_FLIST: ./flists/structured3d_roomtype/structured3d_roomtype/val.flist
TEST_EDGE_FLIST: ./flists/structured3d_roomtype/structured3d_roomtype/test.flist

TRAIN_MASK_FLIST: 
VAL_MASK_FLIST: 
TEST_MASK_FLIST: 

TRAIN_LAYOUT_FLIST: 
VAL_LAYOUT_FLIST:
TEST_LAYOUT_FLIST: 

LR: 0.0001                    # learning rate
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2
BATCH_SIZE: 8                 # input batch size for training
INPUT_SIZE: [256, 512]               # input image size for training 0 for original size
SIGMA: 1.5                      # standard deviation of the Gaussian filter used in Canny edge detector (0: random, -1: no edge)
MAX_ITERS: 100000                # maximum number of iterations to train the model

EDGE_THRESHOLD: 0.5           # edge detection threshold
L1_LOSS_WEIGHT: 1             # l1 loss weight
FM_LOSS_WEIGHT: 10            # feature-matching loss weight
STYLE_LOSS_WEIGHT: 250        # style loss weight
CONTENT_LOSS_WEIGHT: 0.1      # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.1  # adversarial loss weight

GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size

SAVE_INTERVAL: 1000           # how many iterations to wait before saving model (0: never)
SAMPLE_INTERVAL: 1000         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 8               # number of images to sample
EVAL_INTERVAL: 5000              # how many iterations to wait before model evaluation (0: never)
LOG_INTERVAL: 10              # how many iterations to wait before logging training status (0: never)

